spring:
    datasource:
        url: jdbc:mysql://${APP_DB_HOST}:${APP_DB_PORT}/${APP_DB_NAME}?allowPublicKeyRetrieval=true
        username: ${APP_DB_USER}
        password: ${APP_DB_PASS}
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show-sql: true
oc:
    app:
        jwtSecret: ${APP_JWT_SECRET}
        jwtExpirationMs: ${APP_JWT_EXPIRATION_MS}
server:
    port: ${APP_PORT}
